apiVersion: v1
kind: Pod

metadata:
  name: hostpath-writer

spec:
  volumes:
  - name: shared-host-volume
    hostPath:
      path: /data/shared
      type: DirectoryOrCreate

  containers:
  - name: writer

    image: busybox

    command:
    - sh
    - -c
    - |
      while true
      do
        echo "Message from writer pod $(date)" > /shared/shared-log.txt
        sleep 5
      done

    volumeMounts:
    - name: shared-host-volume
      mountPath: /shared